{
 "title": "Api Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Número de Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_threads_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de Tarefas Concluídas",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_completed_items_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Comprimento da Fila de Tarefas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_thread_pool_queue_length",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Número de Timers Ativos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_timer_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}